// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/deep-equal/deep-equal.d.ts
// Type definitions for deep-equal
// Project: https://github.com/substack/node-deep-equal
// Definitions by: remojansen <https://github.com/remojansen>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare module "deep-equal" {

    interface DeepEqualOptions {
        strict: boolean;
    }

    let deepEqual: (
		actual: Object,
		expected: Object,
		opts?: DeepEqualOptions) => boolean;

    export = deepEqual;
}